version: '3'
services:
  nginx:
    ports:
      - 2000:80
  node-app:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
    build: 
      context: .
      args:
       NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js