version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    image: behnamrhp/node-app
    environment:
      - PORT=3000
      - MONGO_USER=behnam
      - MONGO_PASSWORD=myPassword
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - SESSION_SECRED=secret
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: behnam
      MONGO_INITDB_ROOT_PASSWORD: myPassword
    volumes:
      - mongo-db:/data/db
  redis: 
    image: redis:6.2.5-alpine
    ports: 
      - 6379:6379
volumes:
  mongo-db:
