version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    env_file:
      - ./.env
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: behnam
      MONGO_INITDB_ROOT_PASSWORD: myPassword
    volumes:
      - mongo-db:/data/db
  redis: 
    image: redis:6.2.5-alpine
    ports: 
      - 6379:6379
volumes:
  mongo-db:
