version: '3'
services:
  node-app:
    env_file:
      - ./.env
    ports:
      - 3000:3000
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: behnam
      MONGO_INITDB_ROOT_PASSWORD: myPassword
    volumes:
      - mongo-db:/data/db
  redis: 
    image: redis:6.2.5-alpine
    ports: 
      - 6379:6379
volumes:
  mongo-db:
